### ISSUE TITLE
Implement psychrolib in R

### ISSUE THREAD

**Issue by banfelder** [psychrometrics/psychrolib#35]
It may be useful to add an implementation of psychrolib in the R language.

I am creating an R package for this purpose (all functions and tests are ported). Would you be interested in taking a merge request and maintaining the package in this repository, with the goal of ultimately submitting to CRAN?

**Comment by hongyuanjia** [comment]
@banfelder I agree. Are you still working on that? I am also interested in that. I just created a repo which tries to re-implement the `psychrometric` module in R. But that repo is mainly used for EnergyPlus model calibration using [eplusr](https://github.com/hongyuanjia/eplusr).

I would like to join you if you have already started on the re-implementation of psychrolib in R.

**Comment by banfelder** [comment]
@hongyuanjia I've created a fork of this project at [jbanfelder/psychrolib](https://github.com/banfelder/psychrolib), which has the R package implemented in [a branch named r_package](https://github.com/banfelder/psychrolib/tree/r_package). All of the code and tests have been implemented; I still need (at a minimum) to add examples to the roxygen2 documentation, write a proper vignette, and give the whole the thing a double-check. In deference to the original authors, I'd like to hear back from them about whether they are interested in a merge request to fold this work into their repository and maintaining it here before going too much farther.

**Comment by hongyuanjia** [comment]
@banfelder Looks pretty neat! I hope this can be merged into the main repo, too.

**Comment by dmey** [comment]
@banfelder many thanks for your work and interest in contributing back to PsychroLib. Apologies for getting back to you just now. Personally, I think this this would be a good addition to PsychroLib but I would like to clarify a couple of things with you first:

1. Review: I will be happy to review your contribution in line with our current general guidelines however, I do not use R and therefore may not be able to suggest improvements that you may expect from someone who uses R on a day-to-day basis.

2. CRAN: I am happy to submit to CRAN however, as we have not done this before, we may need to some in setting things up from you.

3. Maintenance: will you be able to provide some support for the R version in case bugs are discovered in the future?

I have had a very brief look at your branch and the first thing that I noticed is that you used a different coding convention (please see https://github.com/psychrometrics/psychrolib/blob/master/DEVELOP.md#development-notes). Is there any particular reason for this? We will also need to make sure that the functionality and tests are the same between versions (I have for example seen that you have split these into multiple files -- this is absolutely not a bad things but with PsychroLib we are aiming for consistency).

When we get to the acualt review, please make sure to fork the project so that you will be able to send us a PR (more information at https://github.com/psychrometrics/psychrolib/blob/master/CONTRIBUTING.md.

@didierthevenard do you have anything else to add?

**Comment by didierthevenard** [comment]
@banfelder and @dmey thanks for your contributions and comments. I certainly applaud the effort of converting the library to R and I definitely see value in merging this development into the main repository! As @dmey has pointed out when doing one should aim for consistency, particularly in code layout - for example when comparing different versions in different languages it's much easier if the code is in a single file.
I am really not an expert in R, so I would need to rely on you to make sure tests pass, CRAN is setup properly, etc, however I will be happy to review the code when the time comes.

**Comment by banfelder** [comment]
@didierthevenard  and @dmey Thank you for your comments, and your first look at the R implementation. With regard to @dmey's specific points:

1. Review: I think this would be fine; your review (and that of others) would of course be welcome. We can hope that if the R implementation gains interest there will be other eyes on the code as well, including those of experienced R users and developers.

2. CRAN: I'd be happy to do the CRAN submission; in fact one of my personal goals for this endeavor is to gain some experience in that area.

3. Maintenance: Yes, I'd expect to support the R implementation, both to address any bugs, and also to track future enhancements to PsychroLib.

> ...you used a different coding convention...Is there any particular reason for this? 
I did make some judgement calls when PsychroLib conventions differed from R conventions (taking the lead from the Tidyverse set of libraries). I see two main areas of divergence (but please call out any others that you see):

- multiple small files vs. fewer larger ones: [Tidyverse advice](https://github.com/tidyverse/style/issues/121) is to eschew a monolithic source file; however, since this really only affects the development team, and there is clearly merit in consistency, I can merge these files to more closely track the layout PsychroLib's Python implementation (for both the code and the tests) if we move ahead with integration into this repo.

- use of CamelCase vs. names_with_underscores: This does affect users of the library, and since the tidyverse is [quite explicit](https://style.tidyverse.org/syntax.html#object-names) and consistent about using underscored names, I would argue that use of underscores is appropriate for an R library, as I feel that convenience/consistency for the user outweighs convenience/consistency for the developer.

Thanks again for your consideration.

**Comment by dmey** [comment]
@banfelder 

Re point 1, 2, and 3: Great -- for testing we use CI so we will need to make sure that all the tests are the same across your implementation as well and can be automatically executed. We will get to that stage at the end.

Re code convention: I fully agree with you about specific language conventions -- I too, would have preferred to write Python following PEP8 and have broken the source files down into smaller chunks however, given that this is a rather small library and we wanted to try and keep the API across the different library implementationsas close as possible, and keep maintenance to a minimum (see, for example, [the API documentation page](https://psychrometrics.github.io/psychrolib/api_docs.html)) we decided that the specific language convention was secondary to having a consistent API across the different library implementations. Of course, we could have also used more modern features such such as classes in Python but then again, we tried to keep things as simple and similar as possible between languages -- In the end, I do not think that there is right or wrong answer in the case of PsychroLib...

For me, I think we should change the current R implementation to fit more closely with current other implementation as described in https://github.com/psychrometrics/psychrolib/blob/master/DEVELOP.md#coding-conventions.

This should be rather straightforward to do and I am happy to help with this but we may need to wait until the beginning of August with this as I am busy with other things at the moment.

@didierthevenard do you agree?

@banfelder how does this sound?

**Comment by banfelder** [comment]
@dmey All of this sounds fine.

> for testing we use CI so we will need to make sure that all the tests are the same across your implementation as well and can be automatically executed
This should be straightforward, as I've been using a standard R unit testing library (testthat), and the tests were ported pretty much verbatim from your test suite. Of course, any review would be good and welcome.

 > I think we should change the current R implementation to fit more closely with current other implementation
> This should be rather straightforward to do and I am happy to help with this but we may need to wait until the beginning of August with this as I am busy with other things at the moment.
OK. I can take a first pass at this and get your feedback. I'll start working on that over the coming week. August is a good month for me as well.

**Comment by dmey** [comment]
@banfelder great, thanks. 👍 

 I would suggest creating a fork and moving your current working branch to that fork so that you can create a PR. Please add a clear description of changes/additions so that it will be easier for people to understand the PR in the future. We can use this PR as a starting point after you have taken a first pass with the changes discussed above. Let me know if you have any issues in the meantime and if you'd like me to have a look at particular part of the code.

**Comment by dmey** [comment]
@banfelder was wondering if you are still working on it/ have time to submit the PR -- we have made some updates and one bugfix since you last forked it.

**Comment by jakkalavanya1** [comment]
I am trying to use this in the excel sheet. I am unable to use your PsychroLib_2.2.2_SI macro-enabled excel worksheet as it is in a protected view. I downloaded it from releases.
https://github.com/psychrometrics/psychrolib/releases
I have tried to 'enable all macos', also tried to uncheck 'Enable protected view for files originating from the internet' But still, I can't see anything in the excel sheets. 
Can you tell me how to open this?

**Comment by dmey** [comment]
@jakkalavanya1 please open a new separate issue as your issue has nothing to do with R.

**Comment by jakkalavanya1** [comment]
> @jakkalavanya1 please open a new separate issue as your issue has nothing to do with R.

Sorry, I just did open a new issue.
Thank you.

**Comment by dmey** [comment]
Closing -- see #49.
