### ISSUE TITLE
Fix PsychroLib description for R description file

### ISSUE THREAD

**Issue by dmey** [psychrometrics/psychrolib#64]
Use the same description for repo and file published on CRAN.

**Comment by hongyuanjia** [comment]
I just recalled why I changed the description in the DESCRIPTION in the R package. It was because that this requirement in the DESCRIPTION for packages submitted to CRAN:

```
  The Description field should not start with the package name,
    'This package' or similar.
```

Current there are 3 sentences in the repo description:


1. *PsychroLib is a software library* to enable the calculation of psychrometric properties of moist and dry air.
2. Versions of PsychroLib are available for Python, C, C#, Fortran, R, JavaScript, Microsoft Excel Visual Basic for Applications (VBA).
3. PsychroLib works in both metric (SI) and imperial (IP) systems of units.

Current CRAN description:

*Implementation of 'PsychroLib' `<https://github.com/psychrometrics/psychrolib>` library which contains functions*
to enable the calculation properties of moist and dry air in both metric (SI) and imperial (IP) systems of units.
References: Meyer, D. and Thevenard, D (2019) `<doi.org:10.21105/joss.01137>`.

Which to my opinion is shorter and more concise. BTW, the [python version](https://pypi.org/project/PsychroLib/) does not have a description and [JS version](https://www.nuget.org/packages/PsychroLib) also has a different description. IMO, we can just keep the CRAN version. Any thoughts? @dmey
