### ISSUE TITLE
variables in js version

### ISSUE THREAD

**Issue by rlars9000** [psychrometrics/psychrolib#66]
Mac Os: 10.15.6
Node: v14.11.0

I don't know if these are bugs but it is what I had to do to get this to work:

*Node had an issue with PSYCHROLIB_TOLERANCE not being declared.

*Also with HumRatio in:  this.GetHumRatioFromTWetBulb = function 
    HumRatio = INVALID

*Didn't like log as a variable name in var log = Math.log;  Changed vars to const and let throughout.

*ES Modules in Node >= 14 no longer have require by default. I am new at this but I used import instead of require.

After these changes it worked fine.

**Comment by dmey** [comment]
@rlars9000 thanks for reporting this but I am not sure I understated the issue -- Can you please fill in the template or let me know what commands you are using etc so that I can try to reproduce the issue at my end? If you prefer you can also submit a PR with your changes and I can review it. Re the specifics of your post I tried in Node 14.11.0 as well but could not reproduce your issues --

![image](https://user-images.githubusercontent.com/26348635/93668833-9da00a00-fa8f-11ea-94fe-3f2de5c3a2ea.png)
