### ISSUE TITLE
GetDryBulbFromWetBulb(WetBulb, HumRatio)

### ISSUE THREAD

**Issue by Tokarzewski** [psychrometrics/psychrolib#92]
**Is your feature request related to a problem? Please describe.**
I cant calculate dry bulb temperature from wetbulb temperature and absolute HumRatio.

**Describe the solution you'd like**
Create function that calculates dry bulb temperature from wetbulb temperature and absolute HumRatio.

**Describe alternatives you've considered**
I tried calculating it with existing functions. But it needs enthalpy which needs drybulb...

**Comment by didierthevenard** [comment]
The approach taken in PsychroLib is that dry bulb temperature is always the known quantity; the library always computes some moist-air related quantity from some other moist-air related quantity and (known) dry bulb temperature. What you are asking here is a bit different since you want to calculate dry bulb temperature from two moist-air related quantities.
Your best bet would be to look at function GetHumRatioFromTWetBulb. This function contains formulae that calculate humidity ratio from wet bulb temperature and dry bulb temperature. It looks like the formulae could easily be reworked to calculate dry bulb temperature from humidity ratio and wet bulb temperature, which would provide a solution to your problem. For example this formula:
HumRatio = ((1093 - 0.556 * TWetBulb) * Wsstar - 0.240 * (TDryBulb - TWetBulb)) \
                    / (1093 + 0.444 * TDryBulb - TWetBulb)
can be changed into this:
TDryBulb = ((1093 - 0.556 * TWetBulb) * Wsstar + 0.240 * TWetBulb - HumRatio * (1093 - TWetBulb)) \
                   / (0.444 * HumRatio + 0.240)
which is what you want (you need to rework all three formulae in that function to cover all cases). Care should also be taken in ensuring that the value of TDryBulb that you obtain in the end is realistic, that is, greater than TWetBulb.

**Comment by Tokarzewski** [comment]
@didierthevenard thank you for the solution :)

**Comment by dmey** [comment]
Will close this now. Feel free to reopen if needed.
